background_b: 255
background_g: 86
background_r: 150
rosdistro: 'kinetic

  '
roslaunch:
  uris: {host_test_system__35654: 'http://test-system:35654/'}
rosversion: '1.12.13

  '
run_id: f8bfe296-7ed3-11e8-99cd-b827eb99801d
